<div id="content">
    <div class="container">
        <div class="fullwidth_column">
            <?php
            $content = '';
            foreach ($this->resources as $k => $this->resource) {
                $content .= $this->render('index/Html/resources.phtml');
            }
            //Get out of the way of the normal view scope
            $this->layout()->assign('forms', '');
            if (0 < strlen($content)) {
                $this->layout()->assign('forms', $this->render('index/Html/forms.phtml'));
                echo '<ul id="resources" class="resources">' , $content , '</ul>',
                     'The API base URL is ', Glitch_Registry::getSettings()->workbench->baseUrl;
            } else {
                echo '<p>No documentation available</p>';
            }
            if (Workbench_Model_Application::isDevelopment()) {
                echo '<div id="appDebug">';
                if (0 < count($this->resources->getSkipped())) {
                    echo '<h3>Skipped</h3>', $this->htmlList($this->resources->getSkipped());
                }
                $todos = array(
                    'Implement 3 legged OAuth',
                    'Check if master docblock of a class is required (disabled for now..)',
                    'Implement CSS colors, etc with CSS3 SSAS see http://compass-style.org/ for more info',
                    'Make a HTML5 variant with correct tags, etc..',
                    'Read versions from docblock? Where else could we retrieve versions?',
                );
                echo '<h3>Todo\'s</h3>', $this->htmlList($todos, true), '</div>';
            }
            ?>
        </div>
    </div>
</div>