<?php
$body = $this->response->getBody();
$contentType = $this->response->getHeader('Content-type');
$n = array(PHP_EOL, "\r\n", "\r", "\n");
if (0 === stripos($contentType, 'image/')) {
    $body = sprintf('<img src="data:image/%s;base64,%s" alt="%s" />', $contentType, base64_encode($body), 'image');
} else {
    if ('json' === $this->format) {
        //Woohoo!
        $body = Zend_Json::prettyPrint($body, array(
            'indent' => str_repeat(' ', 4),
        ));
    }

    //Escape single quotes for JS
    $body = trim(str_replace($n, '<br/>', $this->escape(print_r($body, true))));
    //Zend_Json::prettyPrint takes care of addslashes
    if ('json' !== $this->format) {
        $body = addslashes($body);
    }
    $body = $this->hateoas($body, $this->format, $this->apiHost);
}

$headers = trim(str_replace($n, '<br/>', $this->escape(print_r($this->response->getHeadersAsString(), true))));
$request = trim(str_replace($n, '<br/>', $this->escape(print_r($this->request, true))));
$body = trim(str_replace($n, '<br/>', $body));
?>

$('#<?php echo $this->id ?> .request_url').html('<pre><?php echo $this->escape($this->url) ?></pre>');
$('#<?php echo $this->id ?> .request_last').html('<pre><?php echo $request ?></pre>');
$('#<?php echo $this->id ?> .response_code').html('<pre><?php echo $this->escape($this->response->getStatus()) ?></pre>');
$('#<?php echo $this->id ?> .response_headers').html('<pre><?php echo $headers ?></pre>');
$('#<?php echo $this->id ?> .response_time').html('<pre><?php echo $this->responsetime ?> seconds</pre>');
$('#<?php echo $this->id ?> .response_body').html('<pre><?php echo $body ?></pre>');
$('#<?php echo $this->id ?>').slideDown();
$('#<?php echo $this->id ?>_hider').fadeIn();
$('#<?php echo $this->id ?>_button').attr({'value': 'Again!'});