<ul class="togglers">
    <li>
        <a rel="oauth" href="">Toggle OAuth form</a>
    </li>
    <li>
        <a rel="misc" href="">Toggle settings form</a>
    </li>
    <?php
    if (Workbench_Model_Application::isDevelopment()) {
    ?>
    <li>
        <a rel="colorchange" href="">Toggle style form</a>
    </li>
    <?php
    }
    ?>
</ul>
<?php
$form = new Zend_Form(array(
    'decorators' => array('Description', 'FormElements', 'Fieldset', 'Form'),
    'legend' => 'OAuth',
    'description' => 'OAuth settings',
    'elementDecorators' => array('ViewHelper', 'Label', 'HtmlTag'),
    'attribs' => array(
        'class' => 'formtastic config',
        'id' => 'oauth',
    ),
));
$form->addElement('text', 'consumerkey', array('label' => 'OAuth Consumerkey'));
$form->addElement('text', 'consumersecret', array('label' => 'OAuth Consumersecret'));
$form->addElement('select', 'signing', array(
    'label' => 'OAuth Signing method',
    'multiOptions' => array(
        'sha1' => 'SHA1',
        'rsa' => 'RSA',
        'plaintext' => 'Plaintext'
)));

$form->setElementsBelongTo('oauth');
$form->addElement('text', 'realm', array('label' => 'OAuth Realm (Optional)'));
$form->populate(Workbench_Model_Workbench_Endpoint::getOauth());
echo $form;

$form = new Zend_Form(array(
    'decorators' => array('Description', 'FormElements', 'Fieldset', 'Form'),
    'legend' => 'Settings',
    'description' => 'Misc settings',
    'elementDecorators' => array('ViewHelper', 'Label', 'Description', 'HtmlTag'),
    'attribs' => array(
        'class' => 'formtastic config',
        'id' => 'misc',
    ),
));
$form->addElement('text', 'timeout', array(
    'label' => 'Connection timeout',
    'description' => 'seconds',
    'attribs' => array(
        'class' => 'small',
        'maxlength' => 2
    ),
));
$form->setElementsBelongTo('misc');
echo $form;

if (Workbench_Model_Application::isDevelopment()) {
    $links = array(
        '<a id="copyToClipboard" href="">Copy to clipboard</a>',
        '<a id="showStyles" href="">Toggle stylesheet rules</a><div id="showStylesContainer" class="hidden"></div>',
    );
    $form = new Zend_Form(array(
        'decorators' => array('FormElements', array(array('colorchange' => 'ViewHelper'), array('helper' => 'placeholder')), 'Fieldset', 'Form'),
        'legend' => 'Colors!',
        'elementDecorators' => array('ViewHelper', 'Label', 'Description', 'HtmlTag'),
        'attribs' => array(
            'class' => 'formtastic config',
            'id' => 'colorchange'
        ),
        'name' => 'colorchange',
    ));
    $this->placeholder('colorchange')->set($this->htmlList($links, false, array('id' => 'colorchange-links'), false));
    $form->getDecorator('Fieldset')->setOption('id', null);

    $form->addElement('text', 'styleColor', array(
        'label' => 'background color',
        'attribs' => array('class' => 'color'),
    ));
    $form->addElement('text', 'fontColor', array(
        'label' => 'font color',
        'attribs' => array('class' => 'color'),
    ));
    $methods = array('GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'HEAD');
    $methods = array_change_key_case(array_combine($methods, $methods), CASE_LOWER);

    $form->addElement('select', 'styleMethod', array(
        'label' => 'HTTP method',
        'multiOptions' => $methods,
    ));
    $form->addElement('checkbox', 'styleAll', array(
        'label' => 'All methods?',
    ));
    $form->getElement('styleAll')->getDecorator('Label')->setOption('placement', 'APPEND');
    $form->getElement('styleAll')->getDecorator('ViewHelper')->setOption('placement', 'PREPEND');

    $form->addElement('reset', 'resetStyles', array(
        'label' => 'Reset colors',
    ));

    /*$form->addElement('button', 'copyToClipboard', array(
        'label' => 'Copy stylesheet to clipboard',
    ));

    $form->addElement('button', 'showStyles', array(
        'label' => 'Toggle stylesheet rules',
        'description' => '&nbsp;',
    ));*/

    //$form->getElement('copyToClipboard')->removeDecorator('Label');
    $form->getElement('resetStyles')->removeDecorator('Label');
    /*$form->getElement('showStyles')->removeDecorator('Label')->getDecorator('Description')->setOptions(array(
        'escape' => false,
        'id' => 'showStylesContainer',
        'class' => 'hidden',
    ));*/

    echo $form;
}