<?php
$url    = $this->endpoint->getUrl();
$nodeId = trim($this->endpoint->getUseageUrl());
$jslink = '#!/' . $nodeId;

$method = $this->endpoint->getMethod();
$listClass = array($method, 'operation');
?>
<li class="endpoint">
    <ul class="operations">
        <li id="list_<?php echo $nodeId ?>" class="<?php echo implode(' ', $listClass) ?>">
            <div class="heading">
                <h3>
                    <span class="http_method">
                        <a onclick="Docs.toggleOperationContent('<?php echo $nodeId ?>');" href="<?php echo $jslink ?>"><?php echo $method ?></a>
                    </span>
                    <span class="path">
                        <a onclick="Docs.toggleOperationContent('<?php echo $nodeId ?>');" href="<?php echo $jslink ?>"><?php echo $url ?></a>
                    </span>
                </h3>
                <ul class="options">
                    <li>
                        <a onclick="Docs.toggleOperationContent('<?php echo $nodeId ?>');" href="<?php echo $jslink ?>"><?php echo $this->endpoint->getHint() ?></a>
                    </li>
                </ul>
            </div>
            <div id="<?php echo $nodeId ?>" class="content hidden">
                <form method="post" class="sandbox" action="<?php echo $this->url(array('action' => 'rest')) ?>" accept-charset="UTF-8">
                    <div style="margin:0;padding:0;display:inline">
                        <input type="hidden" value="✓" name="misc[utf8]" />
                        <input type="hidden" value="" name="misc[authenticity_token]" />
                    </div>
                    <h4>Description</h4>
                    <p class="description"><?php echo nl2br($this->escape($this->endpoint->getDescription())) ?></p>
                    <h4>Parameters</h4>
                    <table class="fullwidth">
                        <thead>
                            <tr>
                                <th>Parameter</th>
                                <th><?php echo ($this->endpoint->isDisabledCommit() ? 'Default' : '' )?> Value</th>
                                <th>Description</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $fields = $this->endpoint->getFields();
                            $group  = array();
                            foreach ($fields as $fieldName => $field) {
                                $tdCssClasses = array('code');
                                if ($field->isRequired()) {
                                    $tdCssClasses[] = 'required';
                                }
                                ?>
                                <tr>
                                    <td width="100"><?php echo $fieldName ?></td>
                                    <td width="100" class="<?php echo implode(' ', $tdCssClasses) ?>">
                                        <?php echo $field ?>
                                    </td>
                                    <td width="500">
                                        <strong><?php echo $field->getDescription() ?></strong>
                                    </td>
                                </tr>
                                <?php
                            }
                            $fields = $this->endpoint->getQuery();
                            foreach ($fields as $fieldName => $field) {
                                $tdCssClasses = array('code');
                                if ($field->isRequired()) {
                                    $tdCssClasses[] = 'required';
                                }
                                ?>
                                <tr>
                                    <td width="100">
                                    <?php
                                    echo $fieldName;
                                    if (false !== stripos($field->getAttrib('class'), 'multiArrayParam')) {
                                        echo ' <a title="Add row" class="addInputField arrayParamControl" href="/#!/addInputField"><img src="/workbenchResources/gfx/insert.png" alt="Add row" /></a>',
                                             ' <a title="Remove row" class="removeInputField arrayParamControl hidden" href="/#!/removeInputField/" rel="', $field->getFullyQualifiedName(), '"><img src="/workbenchResources/gfx/remove.png" alt="Remove row" /></a>';
                                    }
                                    ?></td>
                                    <td width="100" class="<?php echo implode(' ', $tdCssClasses) ?>">
                                        <?php echo $field ?>
                                    </td>
                                    <td width="500">
                                        <strong><?php echo $field->getDescription() ?></strong>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                    </table>

                    <?php
                    $filters = $this->endpoint->getFilters();
                    if (count($filters)): ?>
                    <h4>Filters</h4>
                    <table class="fullwidth">
                        <thead>
                            <tr>
                                <th width="132">Name</th>
                                <th width="132">Value</th>
                                <th>Description</th>
                            </tr>
                        </thead>

                        <?php foreach ($filters as $filter): ?>
                            <tr>
                                <td><?php echo $this->escape($filter->getName()) ?></td>
                                <td>
<?php
switch ($filter->getConstraint()) {
    case $filter::FILTER_CONSTRAINT_NONE:
        echo $this->formText('filters[' . $filter->getName() . ']', null, array(
            'placeholder' => ''
        ));
        break;
    case $filter::FILTER_CONSTRAINT_VALUES:

        $values = array();
        foreach ($filter->getAllowedValues() as $value) {
            $values[$value] = $value;
        }
        echo $this->formSelect('filters[' . $filter->getName() . ']', null, null, $values);
        break;
    case $filter::FILTER_CONSTRAINT_RANGE:
        echo $this->formText('filters[' . $filter->getName() . '][from]', null, array(
            'placeholder' => 'min. ' . $filter->getRangeMinimum()
        ));
        echo ' to ';
        echo $this->formText('filters[' . $filter->getName() . '][to]', null, array(
            'placeholder' => 'max. ' . $filter->getRangeMaximum()
        ));
        break;
}
?>
                                </td>
                                <td>
                                    <strong><?php echo $this->escape($filter->getDescription()) ?></strong>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                    <?php endif; ?>

                    <?php
                    if (!$this->endpoint->isDisabledCommit()) {
                    ?>
                    <input type="hidden" value="<?php echo $this->endpoint->getMethod() ?>" name="core[http_method]" />
                    <input type="hidden" value="<?php echo $url ?>" name="core[path]" />
                    <input type="hidden" value="<?php echo $nodeId ?>_sandbox_response" name="misc[dom_id]" />
                    <div id="<?php echo $nodeId ?>_sandbox_response_header" class="sandbox_header">
                        <input type="submit" value="Try it out!" name="commit" id="<?php echo $nodeId ?>_sandbox_response_button" class="submit" />
                        <!-- <button class="submit" type="submit"><span class="icon"></span></button> -->
                        <a style="display: none;" onclick="$('#<?php echo $nodeId ?>_sandbox_response').slideUp();$(this).fadeOut();return false;" id="<?php echo $nodeId ?>_sandbox_response_hider" href="#">Hide Response</a>
                        <div class="throbber" style="display:none"></div>
                    </div>
                    <?php
                    }
                    ?>
                </form>

                <div style="display:none" id="<?php echo $nodeId ?>_sandbox_response" class="response">
                    <?php
                    $mapping = array(
                        'response_code' => 'Response Code',
                        'response_body' => 'Response Body / <a href="" class="expandBody">Open</a>',
                        'response_headers' => 'Response Headers',
                        'request_url' => 'Request URL',
                        'request_last' => 'Last Request',
                        'response_time' => 'Response Time',
                    );
                    $order = $this->registry()->query('settings.workbench.view.responseData', array_flip(array_keys($mapping)));
                    if (is_string($order)) {
                        $order = array_flip(array_map('trim', explode(',', $order)));
                    }
                    $order = array_intersect_key($mapping, (array) $order);
                    foreach ($order as $k => $v) {
                        printf('<h4>%s</h4><div class="%s"></div>', $v, $k);
                    }
                    ?>
                </div>
            </div>
        </li>
    </ul>
</li>
